lightway-app-utils: Provide more information on issues with config file
... by returning an `anyhow::Error` instead of just a boolean.

Rename to `validate_configuration_file_path` to better reflect the purpose.

Previously the errors were:

```console
$ ./target/debug/lightway-server --config-file /etc
Error: Config file "/etc" not present
$ ./target/debug/lightway-server --config-file /non-existing
Error: Config file "/non-existing" not present
``

now the errors are:

```console
$ ./target/debug/lightway-server --config-file /non-existing
Error: Invalid configuration file /non-existing

Caused by:
    No such file or directory (os error 2)

$ ./target/debug/lightway-server --config-file /etc
Error: Invalid configuration file /etc

Caused by:
    Not a file
```