lightway-server: Validate that the server key is not world accessible
The new error is:

```
Error: Invalid server key file tests/certs/server.key

Caused by:
    Configuration file is world accessible
```

This also as a side effect validates the presence and that it is a file, which
isn't really needed (since we would otherwise discover this on use) but does no
harm.