lightway-server: tcp: close connection on any receive error
After e.g.
```
recvfrom(22, 0x7f7dc8033830, 1500, 0, NULL, NULL) = -1 ECONNRESET (Connection reset by peer)
```

the socket is no longer valid for read or write, but we only shutdown the
connection on a return of 0, meaning we subsequently hit:

```
sendto(22, "..."..., 265, MSG_NOSIGNAL, NULL, 0) = -1 EPIPE (Broken pipe)
```

which exits the inside I/O loop with:

```
Error: Inside IO loop exited

Caused by:
    0: Inside data handling error
    1: WolfSSL Error: Fatal: code: -308, what: error state on socket
    2: Fatal: code: -308, what: error state on socket
```